export default {
    "Etc/GMT+12": "(GMT-12:00) International Date Line West",
    "Pacific/Midway": "(GMT-11:00) Midway Island, Samoa",
    "Pacific/Honolulu": "(GMT-10:00) Hawaii",
    "US/Alaska": "(GMT-09:00) Alaska",
    "America/Los_Angeles": "(GMT-08:00) Pacific Time (US & Canada)",
    "US/Arizona": "(GMT-07:00) Arizona",
    "America/Managua": "(GMT-06:00) Central America",
    "US/Central": "(GMT-06:00) Central Time (US & Canada)",
    "America/Bogota": "(GMT-05:00) Bogota, Lima, Quito, Rio Branco",
    "US/Eastern": "(GMT-05:00) Eastern Time (US & Canada)",
    "Canada/Atlantic": "(GMT-04:00) Atlantic Time (Canada)",
    "America/Argentina/Buenos_Aires": "(GMT-03:00) Buenos Aires, Georgetown",
    "America/Noronha": "(GMT-02:00) Mid-Atlantic",
    "Atlantic/Azores": "(GMT-01:00) Azores",
    "Etc/Greenwich": "(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London",
    "Europe/Amsterdam": "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "Europe/Helsinki": "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    "Europe/Moscow": "(GMT+03:00) Moscow, St. Petersburg, Volgograd",
    "Asia/Tehran": "(GMT+03:30) Tehran",
    "Asia/Yerevan": "(GMT+04:00) Yerevan",
    "Asia/Kabul": "(GMT+04:30) Kabul",
    "Asia/Yekaterinburg": "(GMT+05:00) Yekaterinburg",
    "Asia/Karachi": "(GMT+05:00) Islamabad, Karachi, Tashkent",
    "Asia/Calcutta": "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    "Asia/Katmandu": "(GMT+05:45) Kathmandu",
    "Asia/Dhaka": "(GMT+06:00) Astana, Dhaka",
    "Asia/Rangoon": "(GMT+06:30) Yangon (Rangoon)",
    "Asia/Bangkok": "(GMT+07:00) Bangkok, Hanoi, Jakarta",
    "Asia/Hong_Kong": "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    "Asia/Seoul": "(GMT+09:00) Seoul",
    "Australia/Adelaide": "(GMT+09:30) Adelaide",
    "Australia/Canberra": "(GMT+10:00) Canberra, Melbourne, Sydney",
    "Asia/Magadan": "(GMT+11:00) Magadan, Solomon Is., New Caledonia",
    "Pacific/Auckland": "(GMT+12:00) Auckland, Wellington",
    "Pacific/Tongatapu": "(GMT+13:00) Nuku'alofa"
}